# Server
server.port=8080

# External API URL (WireMock em Docker)
external.person-api.url=http://localhost:8089

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=person-api

# Prometheus metrics
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms,200ms,500ms,1s,2s

# Configurar histogramas para métricas customizadas
management.metrics.distribution.percentiles-histogram.person.endpoint.response.time=true
management.metrics.distribution.sla.person.endpoint.response.time=50ms,100ms,200ms,500ms,1s,2s,5s
management.metrics.distribution.percentiles.person.endpoint.response.time=0.5,0.75,0.95,0.99,0.999

