{
 "title": "Person API Dashboard",
 "tags": [
  "person-api",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Recursos do Sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_usage{application=\"person-api\"}[5m]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memória Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"person-api\", area=\"heap\"}",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"person-api\", area=\"heap\"}",
     "legendFormat": "Heap Max"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"person-api\", area=\"heap\"}",
     "legendFormat": "Heap Committed"
    }
   ]
  },
  {
   "title": "Threads por Estado",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"person-api\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Taxa de Erro (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  rate(person_endpoint_errors_total{application=\"person-api\"}[5m])\r\n  /\r\n  clamp_min(rate(person_endpoint_requests_total{application=\"person-api\"}[5m]), 1)\r\n) * 100"
    }
   ]
  },
  {
   "title": "Total de Chamadas API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(person_endpoint_requests_total[$__range])"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  rate(person_endpoint_requests_total{application=\"person-api\"}[1m])\r\n  [$__range:]\r\n)"
    }
   ]
  },
  {
   "title": "Percentis",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  histogram_quantile(\r\n    0.50,\r\n    rate(person_endpoint_response_time_seconds_bucket{application=\"person-api\"}[5m])\r\n  )[15m:]\r\n) * 1000",
     "legendFormat": "P50"
    },
    {
     "expr": "max_over_time(\r\n  histogram_quantile(\r\n    0.95,\r\n    rate(person_endpoint_response_time_seconds_bucket{application=\"person-api\"}[5m])\r\n  )[15m:]\r\n) * 1000",
     "legendFormat": "P95"
    },
    {
     "expr": "max_over_time(\r\n  histogram_quantile(\r\n    0.99,\r\n    rate(person_endpoint_response_time_seconds_bucket{application=\"person-api\"}[5m])\r\n  )[15m:]\r\n) * 1000",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Tempo de Resposta do Endpoint (ms)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(person_endpoint_response_time_seconds_sum{application=\"person-api\"}[5m]) / rate(person_endpoint_response_time_seconds_count{application=\"person-api\"}[5m]) * 1000",
     "legendFormat": "Tempo Médio"
    },
    {
     "expr": "histogram_quantile(0.95, rate(person_endpoint_response_time_seconds_bucket{application=\"person-api\"}[5m])) * 1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(person_endpoint_response_time_seconds_bucket{application=\"person-api\"}[5m])) * 1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.50, rate(person_endpoint_response_time_seconds_bucket{application=\"person-api\"}[5m])) * 1000",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Requisições por Segundo (Sucesso vs Erros)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(person_endpoint_requests_total{application=\"person-api\"}[5m]) - rate(person_endpoint_errors_total{application=\"person-api\"}[5m]) ",
     "legendFormat": "Sucesso"
    },
    {
     "expr": "rate(person_endpoint_errors_total{application=\"person-api\"}[5m])",
     "legendFormat": "Erros"
    }
   ]
  },
  {
   "title": "Quantidade de Chamadas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(person_endpoint_requests_total{application=\"person-api\"}[5m]) ",
     "legendFormat": "Taxa de Requisições/s"
    }
   ]
  }
 ]
}